#!/bin/bash
#IP Hunter by aissia
#Youtube Tutorial Modem: https://bit.ly/aryochannel

clear
#-- colors --#
#R='\e[1;31m' #RED
#G='\e[1;32m' #GREEN
#B='\e[1;34m' #BLUE
#Y='\e[1;33m' #YELLOW
#C='\e[1;36m' #CYAN
W='\e[1;37m' #WHITE
##############

#-- colors v2 --#
R='\e[31;1m' #RED
G='\e[32;1m' #GREEN
Y='\e[33;1m' #YELLOW
DB='\e[34;1m' #DARKBLUE
P='\e[35;1m' #PURPLE
LB='\e[36;1m' #LIGHTBLUE

#-- colors v3 --#
BR='\e[3;31m' #RED
BG='\e[3;32m' #GREEN
BY='\e[3;33m' #YELLOW
BDB='\e[3;34m' #DARKBLUE
BP='\e[3;35m' #PURPLE
BLB='\e[3;36m' #LIGHTBLUE

echo -e "$BDB **************************************************"
echo -e " **                                              **"
echo -e "$BDB **$R       SCRIPT MODEM BOLT MF90 by aissia       $DB**"
echo -e " **                                              **"
echo -e "$BDB **************************************************"
echo -e "$BDB **$Y           PILIH OPSI YANG TERSEDIA           $DB**"
echo -e "$BDB **************************************************"
echo -e "$BDB **$G DAFTAR :                                     $DB**"
echo -e "$BDB **$G [\e[36m•1\e[0m$G] Ganti IP Address                        $BDB**"
echo -e "$BDB **$G [\e[36m•2\e[0m$G] Lihat 5 SMS terbaru                     $BDB**"
echo -e "$BDB **$G [\e[36m•3\e[0m$G] Hapus semua SMS                         $BDB**"
echo -e "$BDB **$G [\e[36m•4\e[0m$G] Restart / Reboot                        $BDB**"
echo -e "$BDB **************************************************"
echo -e "$W"
echo -e   ""
echo -e   " Press x or [ Ctrl+C ] • To-Exit-Script"
read -p " Select menu :  "  opt
echo -e   ""
case $opt in
1) clear ;
echo -e Proses ubah ip, mohon ditunggu. . .
echo -e
sleep 3
clear
ipmodem=$(route -n|awk '{print $2}'|grep 192.168|head -n1)
curl -s --header "Referer: http://$ipmodem/index.html" -d 'isTest=false&goformId=LOGIN&password=YWRtaW4xMzI=' http://$ipmodem/goform/goform_set_cmd_process
curl -s --header "Referer: http://$ipmodem/index.html" -d 'isTest=false&notCallback=true&goformId=DISCONNECT_NETWORK' http://$ipmodem/goform/goform_set_cmd_process
sleep 3
curl -s --header "Referer: http://$ipmodem/index.html" -d 'isTest=false&notCallback=true&goformId=CONNECT_NETWORK' http://$ipmodem/goform/goform_set_cmd_process
clear
echo -e Proses ubah ip selesai.
echo -e
sleep 3
/usr/bin/mf90
 ;;
2) clear ;
echo -e Proses cek sms, mohon ditunggu. . .
echo -e
sleep 3
clear
ipmodem=$(route -n|awk '{print $2}'|grep 192.168|head -n1)
URL=http://$ipmodem
REFERER="$URL/index.html"
URL_GET="$URL/goform/goform_get_cmd_process"

curl -s --header "Referer: http://$ipmodem/index.html" -d 'isTest=false&goformId=LOGIN&password=YWRtaW4xMzI=' http://$ipmodem/goform/goform_set_cmd_process
DATA_TOTAL=$(curl -s --header "Referer: $REFERER" $URL_GET\?isTest\=false\&cmd\=sms_data_total\&page=0\&data_per_page\=500\&mem_store\=1\&tags\=10\&order_by\=order+by+id+desc)
LIST=$(echo $DATA_TOTAL | tr -d ' ' | jq -c '.messages | values []'| head -n 5);
clear
echo -e "--------------------------------------"
for SMS in $LIST; do
  NUMBER=$(echo $SMS | jq --raw-output .number)
  CONTENT=$(echo $SMS | jq --raw-output .content | tr '\0' '\n' | xxd -r -p | tr -d '\0')
  echo -e "Dari    : $NUMBER"
  echo -e "Isi SMS : $CONTENT"
  echo -e "--------------------------------------"
done
echo -e
read -n 1 -s -r -p "Press any key to back on menu"
/usr/bin/mf90
 ;;
3) clear ;
echo -e Proses delete sms, mohon ditunggu. . .
echo -e
sleep 3
clear
ipmodem=$(route -n|awk '{print $2}'|grep 192.168|head -n1)
URL=http://$ipmodem
REFERER="$URL/index.html"
URL_SET="$URL/goform/goform_set_cmd_process"
URL_GET="$URL/goform/goform_get_cmd_process"
curl -s --header "Referer: http://$ipmodem/index.html" -d 'isTest=false&goformId=LOGIN&password=YWRtaW4xMzI=' http://$ipmodem/goform/goform_set_cmd_process
DATA_TOTAL=$(curl -s --header "Referer: $REFERER" $URL_GET\?isTest\=false\&cmd\=sms_data_total\&page=0\&data_per_page\=500\&mem_store\=1\&tags\=10\&order_by\=order+by+id+desc)
LIST=$(echo $DATA_TOTAL | tr -d ' ' | jq -c '.messages | values []');
for SMS in $LIST; do
 ID=$(echo $SMS | jq --raw-output .id)
 IDS+="$ID;"
done
if [ ! -z "$ID" ]; then
  DELETE=$(curl -s --header "Referer: $REFERER" -d "isTest=false&goformId=DELETE_SMS&msg_id=$IDS&notCallback=true" $URL_SET | jq --raw-output .result)
 if [ "$DELETE" == "success" ]; then
   echo "All messages deleted successfully."
 else
    echo "Messages could not be deleted."
 fi
fi
 sleep 5
 clear
 echo -e Proses delete sms selesai.
 echo -e
sleep 3
 /usr/bin/mf90
  ;;
4) clear ;
echo -e Proses reboot, mohon ditunggu......
echo -e
adb shell reboot
sleep 3
clear
echo -e
echo -e Done.....
echo -e
sleep 4
/usr/bin/mf90
 ;;

x) exit ;;
*) echo "Anda salah tekan " ; sleep 1 ; /usr/bin/mf90 ;;
esac

